function cost = rover_cost(k_1,psi_end,k_3,w0_max,w0_min,v_max,v_min,x_des,y_des,cx,cy)
%ROVER_COST
%    COST = ROVER_COST(K_1,PSI_END,K_3,W0_MAX,W0_MIN,V_MAX,V_MIN,X_DES,Y_DES,CX,CY)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Mar-2020 22:32:42

t2 = k_1+1.0;
t3 = k_3+1.0;
t4 = psi_end./4.0;
t5 = v_min./2.0;
t6 = v_max./2.0;
t7 = w0_min./2.0;
t8 = w0_max./2.0;
t12 = psi_end.*3.825e-2;
t13 = w0_min.*7.65e-2;
t9 = -t6;
t10 = -t7;
t11 = -t8;
t14 = -t13;
t15 = t5+t9;
t16 = t7+t11;
t17 = t3.*t15;
t18 = t2.*t16;
t19 = -t17;
t20 = -t18;
t21 = t18./2.0;
t24 = (t18-w0_min).^2;
t25 = -(t18-w0_min).^3;
t26 = t18.*7.65e-2;
t22 = t19+v_min;
t23 = t20+w0_min;
t27 = -t26;
t28 = t4+t10+t21;
t32 = t12+t14+t26;
t29 = t28.^2;
t30 = t28.^3;
t31 = t13+t27;
cost = cy.*(psi_end.*(-7.65e-2)+y_des+(t17-v_min).*(t18-w0_min).^3.*(2.0./3.0)+t24.*t31.*(4.0./3.0)+t24.*t32.*2.0+t29.*t31.*(1.6e+1./5.0)+t29.*t32.*(1.6e+1./3.0)+t28.*(t17-v_min).*(8.0./3.0)-t30.*(t17-v_min).*(6.4e+1./2.1e+1)-(t17-v_min).*(t18-w0_min).*2.0+t29.*(t17-v_min).*(t18-w0_min).*(1.6e+1./3.0)-t24.*t28.*(t17-v_min).*(1.6e+1./5.0)-t28.*t31.*(t18-w0_min).*4.0-t28.*t32.*(t18-w0_min).*(3.2e+1./5.0)).^2+cx.*(t17.*2.0-v_min.*2.0+x_des+t28.*t31.*(8.0./3.0)+t28.*t32.*4.0-t30.*t31.*(6.4e+1./2.1e+1)-t30.*t32.*(1.6e+1./3.0)-t24.*(t17-v_min).*(4.0./3.0)-t29.*(t17-v_min).*(1.6e+1./5.0)-t31.*(t18-w0_min).*2.0-t32.*(t18-w0_min).*(8.0./3.0)+t31.*(t18-w0_min).^3.*(2.0./3.0)+t32.*(t18-w0_min).^3.*(1.6e+1./1.5e+1)+t28.*(t17-v_min).*(t18-w0_min).*4.0-t24.*t28.*t31.*(1.6e+1./5.0)-t24.*t28.*t32.*(1.6e+1./3.0)+t29.*t31.*(t18-w0_min).*(1.6e+1./3.0)+t29.*t32.*(t18-w0_min).*(6.4e+1./7.0)).^2;
