function cost = segway_cost(k_1,k_2,w_max,v_max,x_des,y_des)
%SEGWAY_COST
%    COST = SEGWAY_COST(K_1,K_2,W_MAX,V_MAX,X_DES,Y_DES)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    12-Mar-2020 09:01:16

t2 = k_1.^2;
t3 = w_max.^2;
t4 = v_max.*(4.1e+1./2.5e+2);
t5 = v_max.*(4.1e+1./5.0e+2);
t8 = v_max.*(4.1e+1./1.0e+3);
t10 = v_max.*(1.23e+2./1.0e+3);
t6 = k_2.*t4;
t7 = k_2.*t5;
t9 = k_2.*t8;
t11 = k_2.*t10;
t12 = t5+t7;
t13 = t8+t9;
t14 = (k_1.*t12.*w_max)./1.0e+1;
t15 = (k_1.*t13.*w_max)./1.0e+1;
t16 = t2.*t3.*t13.*8.2e-3;
t17 = -t16;
t18 = t14+t15;
t19 = t10+t11+t17;
t20 = k_1.*t18.*w_max.*(4.1e+1./5.0e+2);
t21 = -t20;
t22 = (k_1.*t19.*w_max)./1.0e+1;
t23 = t4+t6+t17+t21;
t24 = t18+t22;
t25 = (k_1.*t23.*w_max)./1.0e+1;
t26 = k_1.*t24.*w_max.*(4.1e+1./5.0e+2);
cost = (t16+t20+t26-v_max.*(1.23e+2./5.0e+2)+x_des-k_2.*v_max.*(1.23e+2./5.0e+2)+k_1.*w_max.*(t24+t25).*(4.1e+1./5.0e+2)).^2+(t24+t25-y_des-(k_1.*w_max.*(t16+t20+t26-v_max.*(4.1e+1./2.0e+2)-k_2.*v_max.*(4.1e+1./2.0e+2)))./1.0e+1).^2;
